name: Deploy W2-UI to Dev Server

on:
  push:
    branches:
      - main
      - cicd

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.12.1]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Package
        run: |
          npm ci --legacy-peer-deps
      
      - name: Build Static Files
        run: |
          npm run build

